version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: test_db
    ports: 
      - "27017:27017"
    volumes: 
      - ./initMongo/:/docker-entrypoint-initdb.d/
    hostname: "127.0.0.1"
    command: mongod --smallfiles --replSet mongo-rs